version: "3"

services: 
    nodejs:
        build: .
        ports: 
            - "3000:3000"
        volumes: 
            - .:/usr/app

    db:
        image: mysql
        restart: always
        ports: 
            - "3306:3306"
        volumes: 
            - ./sql:/home/sql
        environment:
            MYSQL_ROOT_PASSWORD: pass
            MYSQL_DATABASE: comentarios