version: "3"

services: 
    nodejs:
        build: .
        command: npm start
        ports: 
            - "3000:3000"

        volumes: 
            - ./node:/usr/app
        networks:
            - gateway


    db:
        image: mysql
        restart: always
        
        ports: 
            - "3306:3306"
        volumes: 
            - ./sql:/home/sql
        environment:
            MYSQL_ROOT_PASSWORD: pass
            MYSQL_DATABASE: comentarios
        networks:
            - gateway

networks:
    gateway: {}
  